syntax on

set noerrorbells
set tabstop=4 softtabstop=4
set shiftwidth=4
set expandtab
set smartindent
set number relativenumber
set hidden
set nobackup
set noswapfile
set smartcase
set undodir=~/.vim/undodir
set undofile
set incsearch
set noshowmode
set shell=/usr/bin/zsh
set scrolloff=999

autocmd FileType
    \ html,css,javascript,javascriptreact
    \ setlocal shiftwidth=2 tabstop=2

imap jk <Esc>
"Tab quick switch map
nnoremap tj :tabprevious<CR>
nnoremap tk :tabnext<CR>

set colorcolumn=80
highlight colorcolumn ctermbg=white

call plug#begin('~/.vim/plugged')

Plug 'vim-utils/vim-man'

" -- THEMES
Plug 'joshdick/onedark.vim'

" -- AIRLINE
Plug 'vim-airline/vim-airline'

" -- GIT
Plug 'tpope/vim-fugitive'

" -- SURROUND
Plug 'tpope/vim-surround'

call plug#end()

colorscheme onedark

" ---- Set custom airline ---- "
function! InitAirline()
    let g:airline_section_z = airline#section#create(['windowswap', 'obsession', 'linenr', ' :%3v'])
    let g:airline_section_b = airline#section#create(['branch'])
    let g:airline_symbols.linenr = ''
    let g:airline_symbols.maxlinenr = ''
endfunction
autocmd VimEnter * call InitAirline()
call InitAirline()
" ---------------------------- "

