# Path to oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="af-magic"

# Plugins loaded
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
plugins=(git gh yarn pip docker)

source $ZSH/oh-my-zsh.sh

# Configs that should be available to all machine
export LANG=en_US.UTF-8
export SHELL=`which zsh`
export EDITOR='nvim'
alias vless="/usr/share/nvim/runtime/macros/less.sh"

# Load user configs
# This is usually specific to each machines
source $HOME/.config.zsh
